title: Ayush Kumar - Portfolio
description: "Pursuing B.Tech Degree from Ram Devi Jindal College."
author: "Ayush Kumar"
role: "B.Tech CSE Student"
email: "ayushkumar71643@gmail.com"
github: "AYUSH-71643"
linkedin: "ayushkumar71643"
baseurl: "/PortfolioWeb" 
url: "https://AYUSH-71643.github.io"
